# -*- coding: utf-8 -*-
"""Worldometer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1soK593nwOdA4ET_L9n0fqZhFLpLpttNh

# [COVID-19 Worldometer](https://www.worldometers.info/coronavirus/)
"""

import requests
from bs4 import BeautifulSoup

link = 'https://www.worldometers.info/coronavirus/'

country = input('Enter country')
link = link + '/country/' + country
html_text = requests.get(link).text
soup = BeautifulSoup(html_text, 'lxml')
print(soup.prettify())

info_divs = soup.find('div', class_="content-inner").findAll('div', id='maincounter-wrap')
print(info_divs)

for block in info_divs[:3]:
    title = block.h1.text
    number = block.span.text
    print(title, number)